#!/bin/bash

echo "🚀 VPNCN2 Backend Setup"
echo "======================"

echo ""
echo "The ngrok URL is blocked by firewall. Here's how to run your backend locally:"
echo ""

echo "1. Make sure your backend server is running on port 3000"
echo "   (or change the port in lib/core/config/flavor.dart)"
echo ""

echo "2. If you don't have a backend server, here are quick options:"
echo ""

echo "   Option A: Simple Node.js Express server"
echo "   ---------------------------------------"
echo "   mkdir backend && cd backend"
echo "   npm init -y"
echo "   npm install express cors"
echo "   cat > server.js << 'EOF'"
echo "   const express = require('express');"
echo "   const cors = require('cors');"
echo "   const app = express();"
echo "   app.use(cors());"
echo "   app.use(express.json());"
echo "   "
echo "   app.post('/api/auth/login', (req, res) => {"
echo "     console.log('Login attempt:', req.body);"
echo "     res.json({"
echo "       data: {"
echo "         id: 1,"
echo "         username: req.body.account,"
echo "         email: req.body.account + '@example.com',"
echo "         fullName: 'Test User',"
echo "         token: 'fake-token-' + Date.now()"
echo "       }"
echo "     });"
echo "   });"
echo "   "
echo "   app.listen(3000, () => console.log('Server running on port 3000'));"
echo "   EOF"
echo "   node server.js"
echo ""

echo "   Option B: Python Flask server"
echo "   -----------------------------"
echo "   pip install flask flask-cors"
echo "   cat > server.py << 'EOF'"
echo "   from flask import Flask, request, jsonify"
echo "   from flask_cors import CORS"
echo "   "
echo "   app = Flask(__name__)"
echo "   CORS(app)"
echo "   "
echo "   @app.route('/api/auth/login', methods=['POST'])"
echo "   def login():"
echo "       data = request.json"
echo "       print(f'Login attempt: {data}')"
echo "       return jsonify({"
echo "           'data': {"
echo "               'id': 1,"
echo "               'username': data.get('account'),"
echo "               'email': f'{data.get(\"account\")}@example.com',"
echo "               'fullName': 'Test User',"
echo "               'token': f'fake-token-{hash(str(data))}'"
echo "           }"
echo "       })"
echo "   "
echo "   if __name__ == '__main__':"
echo "       app.run(port=3000, debug=True)"
echo "   EOF"
echo "   python server.py"
echo ""

echo "3. Test your backend:"
echo "   curl -X POST http://localhost:3000/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"account\": \"phunguyen10\", \"password\": \"12345678\"}'"
echo ""

echo "4. If successful, your Flutter app should now work!"
echo ""

echo "Current Flutter app configuration:"
echo "=================================="
grep -A 5 "case Environment.development:" lib/core/config/flavor.dart
